// Sample of real triaged runs — generated from data/traces/real_cards.jsonl.
// Used as the offline fallback so the dashboard works without a live API.
// Real-time triage output comes from the FastAPI backend with a live model.

import type { TriageCard, TaxonomyCategory } from './api';

export const DEMO_CARDS: TriageCard[] = [
  {
    "run_id": "openhands-astropy__astropy-14365",
    "task_id": "astropy__astropy-14365",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 35 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-astropy__astropy-14995",
    "task_id": "astropy__astropy-14995",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 38 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-astropy__astropy-6938",
    "task_id": "astropy__astropy-6938",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 40 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-astropy__astropy-7746",
    "task_id": "astropy__astropy-7746",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 35 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-10914",
    "task_id": "django__django-10914",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 30 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-10924",
    "task_id": "django__django-10924",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 32 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11001",
    "task_id": "django__django-11001",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 38 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11019",
    "task_id": "django__django-11019",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 30 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11039",
    "task_id": "django__django-11039",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 37 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11049",
    "task_id": "django__django-11049",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 35 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11099",
    "task_id": "django__django-11099",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "ENVIRONMENT",
    "secondary_category": "VERIFICATION",
    "confidence": 0.62,
    "classifier": "llm",
    "root_cause": "The agent's fix is correct (changing `^...$` to `\\A...\\Z` in both validators), and local tests passed at step 35. However, the grading harness reports `passed=False` with `total=None`, indicating the test runner failed to execute rather than tests actually failing. Throughout the trajectory, the agent encountered repeated environment failures (missing `python` binary at step 16, missing `pytest` module at step 23, missing `manage.py` at step 25, missing `django` module at step 32), requiring a `pip install -e .` workaround at step 34. The grading environment likely suffered similar dependency issues, preventing the harness from running the tests at all.",
    "evidence": [
      {
        "step_index": 16,
        "excerpt": "cd . && python -c \"\nfrom django.contrib.auth.validators import ASCIIUsernameValidator, UnicodeUsernameValidator\nfrom django.core.exceptions import ValidationError\n\nascii_v = ASCIIUsernameValidator()\nu",
        "why": "python binary not found, first environment failure"
      },
      {
        "step_index": 23,
        "excerpt": "cd . && python3 -m pytest tests/auth_tests/test_validators.py::UsernameValidatorsTests -xvs",
        "why": "pytest module not found, second environment failure"
      },
      {
        "step_index": 25,
        "excerpt": "cd . && python3 manage.py test auth_tests.test_validators.UsernameValidatorsTests -v 2",
        "why": "manage.py not found at expected path, wrong path/environment"
      },
      {
        "step_index": 32,
        "excerpt": "cd tests && python3 runtests.py auth_tests.test_validators.UsernameValidatorsTests -v 2",
        "why": "Django module not found when running runtests.py directly"
      },
      {
        "step_index": 34,
        "excerpt": "cd . && python3 -m pip install -e . --quiet",
        "why": "Agent had to install Django via pip install -e . to fix environment"
      },
      {
        "step_index": 35,
        "excerpt": "cd tests && python3 runtests.py auth_tests.test_validators.UsernameValidatorsTests -v 2",
        "why": "After environment fix, local tests passed correctly with the new regex"
      }
    ],
    "owner": "environment",
    "recommended_action": "Fix the environment image / setup script. Capture the exact missing dependency and pin it. Escalate to infra if the base image is wrong.",
    "prevention": "Harden the sandbox base image; add a dependency pre-check step; snapshot known-good environments per repo.",
    "taxonomy_version": "0.2.0",
    "provider": "anthropic:claude-sonnet-4-6",
    "fix_suggestion": "Pin the missing dependency in the sandbox base image or setup script. Add a pre-run smoke test that verifies the environment imports all required packages before the agent starts. Snapshot known-good environments per repo and tag them in the run manifest."
  },
  {
    "run_id": "openhands-django__django-11133",
    "task_id": "django__django-11133",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 35 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11179",
    "task_id": "django__django-11179",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 34 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11283",
    "task_id": "django__django-11283",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 30 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11422",
    "task_id": "django__django-11422",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 28 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11564",
    "task_id": "django__django-11564",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 33 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11583",
    "task_id": "django__django-11583",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 38 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11620",
    "task_id": "django__django-11620",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 34 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11630",
    "task_id": "django__django-11630",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 35 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11742",
    "task_id": "django__django-11742",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 31 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11797",
    "task_id": "django__django-11797",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 30 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11815",
    "task_id": "django__django-11815",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 39 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11848",
    "task_id": "django__django-11848",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "TOOL_USE",
    "secondary_category": "REASONING",
    "confidence": 0.92,
    "classifier": "llm",
    "root_cause": "The agent's patch effectively deleted the entire `django/utils/http.py` file (reducing it from ~160 lines to 42 lines, as seen in step 33), removing all imports, constants, and other functions while attempting to edit just the `parse_http_date` function. This catastrophic overwrite was the primary failure \u2014 the file was truncated/replaced incorrectly rather than surgically edited. The final patch confirms this: it shows 160 lines of deletions with only 3 lines remaining, meaning all the necessary constants like `RFC1123_DATE` were destroyed, causing the `name 'RFC1123_DATE' is not defined` errors at step 31.",
    "evidence": [
      {
        "step_index": 31,
        "excerpt": "cd . && python3 << 'EOF'\nimport sys\nimport importlib\n\n# Force reimport\nif 'django.utils.http' in sys.modules:\n    del sys.modules['django.utils.http']\nif 'django.utils' in sys.modules:\n    del sys.mod",
        "why": "Runtime errors show 'RFC1123_DATE is not defined' for all test cases, indicating the constant definitions were removed from the file during editing."
      },
      {
        "step_index": 33,
        "excerpt": "wc -l django/utils/http.py",
        "why": "The file was reduced to only 42 lines from an original ~160 lines, confirming the file was catastrophically truncated."
      },
      {
        "step_index": 29,
        "excerpt": "head -200 django/utils/http.py | tail -50",
        "why": "The head/tail output showed the parse_http_date function was present but the module-level constants and imports were apparently already gone or about to be destroyed."
      }
    ],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering with the repeated-failure step indices. Distinguish from REASONING: here the *plan* may be fine.",
    "prevention": "Add edit-application validation with retry/repair; detect command repetition and force a strategy change; inject workspace path at agent init so it never has to guess.",
    "taxonomy_version": "0.2.0",
    "provider": "anthropic:claude-sonnet-4-6",
    "fix_suggestion": "Add edit-application validation after every FILE_EDIT: verify the modified file still parses (Python: `ast.parse`). Detect command repetition \u2014 if the same command fails 3 times with identical output, inject: 'You are repeating the same failing action. Re-read the file and change your approach.'"
  },
  {
    "run_id": "openhands-django__django-11905",
    "task_id": "django__django-11905",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 34 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11910",
    "task_id": "django__django-11910",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 36 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11964",
    "task_id": "django__django-11964",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 32 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-11999",
    "task_id": "django__django-11999",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 33 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12113",
    "task_id": "django__django-12113",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 29 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12125",
    "task_id": "django__django-12125",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 32 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12184",
    "task_id": "django__django-12184",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 36 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12284",
    "task_id": "django__django-12284",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 29 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12286",
    "task_id": "django__django-12286",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 28 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12308",
    "task_id": "django__django-12308",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 28 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12453",
    "task_id": "django__django-12453",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 28 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12470",
    "task_id": "django__django-12470",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 28 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12497",
    "task_id": "django__django-12497",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 40 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12589",
    "task_id": "django__django-12589",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 30 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12700",
    "task_id": "django__django-12700",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "TOOL_USE",
    "secondary_category": "ENVIRONMENT",
    "confidence": 0.82,
    "classifier": "llm",
    "root_cause": "The agent attempted to edit the file but introduced a syntax/indentation error (IndentationError: unexpected indent at line 1 of debug.py), indicating a malformed patch or edit that corrupted the file. Additionally, the environment lacked the standard 'python' binary (only 'python3' was available), causing early verification failures. After restoring the file via git checkout, the agent ran out of steps before re-applying the fix, leaving no final patch.",
    "evidence": [
      {
        "step_index": 20,
        "excerpt": "cd . && python -c \"\nfrom django.views.debug import SafeExceptionReporterFilter\nimport pprint\n\nfilter = SafeExceptionReporterFilter()\n\n# Test setting with nested lists and dicts\ntest_setting = {\n    'f",
        "why": "Agent ran 'python' command which returned exit=127 (command not found), indicating the environment only has 'python3', not 'python'."
      },
      {
        "step_index": 29,
        "excerpt": "cd . && python3 -c \"\nfrom django.views.debug import SafeExceptionReporterFilter\nimport pprint\n\nfilter = SafeExceptionReporterFilter()\n\n# Test setting with nested lists and dicts\ntest_setting = {\n    '",
        "why": "Running python3 revealed an IndentationError at line 1 of debug.py ('unexpected indent'), showing a previous edit had corrupted the file - the method body was written without the class context."
      },
      {
        "step_index": 33,
        "excerpt": "cd . && git checkout django/views/debug.py",
        "why": "Agent had to run 'git checkout django/views/debug.py' to restore the file, confirming the prior edit was malformed."
      },
      {
        "step_index": 37,
        "excerpt": "wc -l django/views/debug.py",
        "why": "Agent was still exploring the file (checking line count) at step 37 of 38 steps total, meaning it ran out of steps before re-applying the fix, producing no final patch."
      }
    ],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering with the repeated-failure step indices. Distinguish from REASONING: here the *plan* may be fine.",
    "prevention": "Add edit-application validation with retry/repair; detect command repetition and force a strategy change; inject workspace path at agent init so it never has to guess.",
    "taxonomy_version": "0.2.0",
    "provider": "anthropic:claude-sonnet-4-6",
    "fix_suggestion": "Add edit-application validation after every FILE_EDIT: verify the modified file still parses (Python: `ast.parse`). Detect command repetition \u2014 if the same command fails 3 times with identical output, inject: 'You are repeating the same failing action. Re-read the file and change your approach.'"
  },
  {
    "run_id": "openhands-django__django-12708",
    "task_id": "django__django-12708",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 38 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  },
  {
    "run_id": "openhands-django__django-12747",
    "task_id": "django__django-12747",
    "agent": "openhands",
    "model": "claude-haiku-4-5-20251001",
    "primary_category": "IMPLEMENTATION_STALL",
    "secondary_category": null,
    "confidence": 0.72,
    "classifier": "rule",
    "root_cause": "No file edits in 36 steps; no patch produced. Agent explored without committing any change.",
    "evidence": [],
    "owner": "agent_framework",
    "recommended_action": "Escalate to engineering: the agent loop must gate 'finish' on having produced at least one file edit. Show the step where understanding was reached and the remaining turn count at that point.",
    "prevention": "Add a hard rule: 'finish' is disallowed unless at least one file edit has been made; warn the agent after N exploration-only turns with no edits; consider a planning step that commits a skeleton edit early to anchor subsequent refinement.",
    "taxonomy_version": "0.2.0",
    "provider": "rule-based",
    "fix_suggestion": "Gate `finish` on at least one FILE_EDIT having been observed. After every N exploration-only turns with no edit, inject a forced prompt: 'You have not modified any files yet. You must now commit to an implementation and call edit_file.' Consider a mandatory skeleton-edit step after the planning phase."
  }
];

export const DEMO_TAXONOMY: TaxonomyCategory[] = [
  {
    "code": "SCOPING",
    "name": "Task scoping / underspecification",
    "definition": "The task as given was ambiguous, under-constrained, or missing context the agent needed. The agent solved the wrong problem, or a plausible-but-incorrect interpretation of the problem.",
    "owner": "task_author",
    "signals": [
      "agent's solution addresses a different symptom than the test checks",
      "agent asks no clarifying questions on an ambiguous prompt",
      "final patch is plausible but tests assert different behavior",
      "problem statement references files/behavior not in the repo"
    ],
    "recommended_action": "Educate the task author: provide a scoping template (acceptance criteria, target files, reproduction steps). Do not escalate to eng.",
    "prevention": "Add a pre-flight task-quality check that flags vague specs before a run starts; offer a task template in the product."
  },
  {
    "code": "ENVIRONMENT",
    "name": "Environment / dependency setup",
    "definition": "The sandbox could not be brought to a working state: missing dependencies, wrong language/runtime version, build failures, or package-resolution errors unrelated to the agent's code changes.",
    "owner": "environment",
    "signals": [
      "ModuleNotFoundError / ImportError before any edit",
      "pip/npm/poetry install failures",
      "version mismatch errors (python, node, compiler)",
      "missing system library or binary"
    ],
    "recommended_action": "Fix the environment image / setup script. Capture the exact missing dependency and pin it. Escalate to infra if the base image is wrong.",
    "prevention": "Harden the sandbox base image; add a dependency pre-check step; snapshot known-good environments per repo."
  },
  {
    "code": "CONTEXT_RETRIEVAL",
    "name": "Context retrieval / navigation failure",
    "definition": "The agent failed to find or read the relevant code. It edited the wrong file, missed the actual implementation, or never located the symbol it needed despite it existing in the repo.",
    "owner": "agent_framework",
    "signals": [
      "agent edits a file unrelated to the failing test",
      "repeated failed grep/find/ls before giving up",
      "agent claims a symbol doesn't exist when it does",
      "never opens the file containing the bug"
    ],
    "recommended_action": "Escalate to engineering with the trajectory showing the missed file. Note where retrieval broke down (search vs ranking vs read).",
    "prevention": "Improve code-search/indexing; add repo-map priming; raise read budget for large repos."
  },
  {
    "code": "REASONING",
    "name": "Model reasoning / logic error",
    "definition": "The agent found the right place and understood the task, but the fix is logically wrong: incorrect algorithm, wrong edge-case handling, or a misunderstanding of the code's semantics.",
    "owner": "model",
    "signals": [
      "correct file edited, but tests fail on logic/assertion",
      "off-by-one, wrong condition, wrong return value",
      "fix addresses the happy path but breaks an edge case",
      "agent's stated plan is sound but implementation diverges"
    ],
    "recommended_action": "Candidate for a stronger/different model or a routing change. Capture as a reasoning-eval case; consider model escalation.",
    "prevention": "Route hard-reasoning tasks to a stronger model; add a self-review / test-first step before finishing."
  },
  {
    "code": "VERIFICATION",
    "name": "Verification / self-checking failure",
    "definition": "The agent produced a reasonable change but never ran (or misread) the tests, declared success prematurely, or its own verification disagreed with the grading harness.",
    "owner": "agent_framework",
    "signals": [
      "agent calls finish without running the test suite",
      "agent runs tests, sees failures, finishes anyway",
      "agent runs a different test command than the grader",
      "premature 'the fix is complete' with no green run"
    ],
    "recommended_action": "Escalate to engineering: the agent loop should not finish on a red or unverified state. Provide the step where it gave up checking.",
    "prevention": "Make 'tests green' a hard gate before finish; align the agent's test command with the grading harness."
  },
  {
    "code": "TOOL_USE",
    "name": "Tool-use / action-formatting error",
    "definition": "The agent's actions were malformed or misused tools: broken edit syntax, patches that don't apply, repeated identical failing commands, or thrashing without progress.",
    "owner": "agent_framework",
    "signals": [
      "edit/patch repeatedly fails to apply",
      "same command issued 3+ times with identical failure",
      "malformed diff / wrong file path in edit action",
      "agent loops on a tool error without adapting"
    ],
    "recommended_action": "Escalate to engineering with the repeated-failure step indices. Distinguish from REASONING: here the *plan* may be fine.",
    "prevention": "Add edit-application validation with retry/repair; detect command repetition and force a strategy change."
  },
  {
    "code": "RESOURCE_LIMIT",
    "name": "Resource / budget exhaustion",
    "definition": "The run hit a hard limit before finishing: step/iteration cap, context-window overflow, wall-clock timeout, or token/cost budget.",
    "owner": "agent_framework",
    "signals": [
      "run terminates at max iterations",
      "context-window / token-limit errors",
      "timeout / wall-clock cap reached mid-task",
      "truncated observations causing lost context"
    ],
    "recommended_action": "Assess whether the task was too large for the budget (educate user on decomposition) or the agent was inefficient (escalate). Report ACU/cost so spend surprises are visible.",
    "prevention": "Right-size budgets per task complexity; add task decomposition; compress context; surface spend estimates before long runs."
  },
  {
    "code": "INFRA_ERROR",
    "name": "Infrastructure / platform error",
    "definition": "A failure in the platform itself, not the agent's decisions: API rate limits, provider 5xx, network errors, sandbox crashes, or framework exceptions/stack traces.",
    "owner": "environment",
    "signals": [
      "429 / rate-limit from model provider",
      "500/503 from API; connection reset; DNS failure",
      "framework traceback unrelated to task code",
      "sandbox container died / OOM-killed"
    ],
    "recommended_action": "Escalate to infra/platform on-call. These are retryable and should not count against the agent's quality metrics.",
    "prevention": "Add retries with backoff; multi-provider failover; health checks; separate infra failures from quality failures in dashboards."
  },
  {
    "code": "OTHER",
    "name": "Unclassified / mixed",
    "definition": "The failure does not fit a single category above, or the evidence is insufficient to attribute a root cause with confidence.",
    "owner": "unknown",
    "signals": [
      "ambiguous evidence",
      "multiple co-occurring causes"
    ],
    "recommended_action": "Flag for human review. Capture as a candidate for a future taxonomy category if the pattern recurs.",
    "prevention": "Monitor OTHER rate; promote recurring patterns to new categories."
  }
];

export const DEMO_RUNS: unknown[] = [{"run_id": "oh-env-001", "agent": "openhands", "model": "claude-sonnet-4-6", "task": {"task_id": "pallets__flask-4992", "source": "swe-bench", "repo": "pallets/flask", "base_commit": null, "problem_statement": "Config.from_file should support custom loaders.", "gold_patch": null, "test_directives": []}, "steps": [{"index": 0, "action_type": "command", "content": "python -m pytest tests/test_config.py", "observation": {"content": "ImportError: cannot import name 'tomllib'", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}, {"index": 1, "action_type": "command", "content": "pip install tomli", "observation": {"content": "ERROR: Could not find a version that satisfies the requirement tomli", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}, {"index": 2, "action_type": "error", "content": "Unable to set up environment; aborting.", "observation": null, "timestamp": null, "metadata": {}, "failed": false}], "final_patch": null, "test_result": {"passed": false, "total_tests": null, "passed_tests": null, "failed_tests": null, "error_tests": null, "raw_log": ""}, "resolved": false, "wall_time_seconds": null, "total_tokens": null, "total_cost_usd": null, "error": null, "metadata": {}, "step_count": 3, "produced_patch": false, "failed": true, "content_hash": "b584d84f4dee7646"}, {"run_id": "oh-infra-001", "agent": "openhands", "model": "claude-sonnet-4-6", "task": {"task_id": "django__django-15789", "source": "swe-bench", "repo": "django/django", "base_commit": null, "problem_statement": "Add encoder parameter to django.utils.html.json_script.", "gold_patch": null, "test_directives": []}, "steps": [{"index": 0, "action_type": "file_read", "content": "django/utils/html.py", "observation": {"content": "<file contents>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 1, "action_type": "model_call", "content": "plan the fix", "observation": {"content": "anthropic.RateLimitError: Error code 429 - overloaded_error", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}, {"index": 2, "action_type": "model_call", "content": "retry plan", "observation": {"content": "anthropic.RateLimitError: Error code 429 - overloaded_error", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}], "final_patch": null, "test_result": {"passed": false, "total_tests": null, "passed_tests": null, "failed_tests": null, "error_tests": null, "raw_log": ""}, "resolved": false, "wall_time_seconds": null, "total_tokens": null, "total_cost_usd": null, "error": null, "metadata": {}, "step_count": 3, "produced_patch": false, "failed": true, "content_hash": "f4c727a178e0e3bf"}, {"run_id": "oh-res-001", "agent": "openhands", "model": "claude-sonnet-4-6", "task": {"task_id": "sympy__sympy-21055", "source": "swe-bench", "repo": "sympy/sympy", "base_commit": null, "problem_statement": "refine() does not simplify some complex expressions.", "gold_patch": null, "test_directives": []}, "steps": [{"index": 0, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 0", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 1, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 1", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 2, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 2", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 3, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 3", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 4, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 4", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 5, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 5", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 6, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 6", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 7, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 7", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 8, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 8", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 9, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 9", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 10, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 10", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 11, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 11", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 12, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 12", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 13, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 13", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 14, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 14", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 15, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 15", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 16, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 16", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 17, "action_type": "command", "content": "grep -rn refine sympy/assumptions/ # attempt 17", "observation": {"content": "<long output>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 18, "action_type": "error", "content": "Agent reached maximum iterations (18) without finishing the task.", "observation": null, "timestamp": null, "metadata": {}, "failed": false}], "final_patch": null, "test_result": {"passed": false, "total_tests": null, "passed_tests": null, "failed_tests": null, "error_tests": null, "raw_log": ""}, "resolved": false, "wall_time_seconds": null, "total_tokens": null, "total_cost_usd": null, "error": null, "metadata": {}, "step_count": 19, "produced_patch": false, "failed": true, "content_hash": "3ce9316c00a5c713"}, {"run_id": "oh-ctx-001", "agent": "openhands", "model": "claude-sonnet-4-6", "task": {"task_id": "scikit-learn__scikit-learn-13496", "source": "swe-bench", "repo": "scikit-learn/scikit-learn", "base_commit": null, "problem_statement": "Expose warm_start in IsolationForest.", "gold_patch": null, "test_directives": []}, "steps": [{"index": 0, "action_type": "command", "content": "grep -rn 'warm_start' sklearn/ensemble/_iforest.py", "observation": {"content": "", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}, {"index": 1, "action_type": "file_edit", "content": "edited sklearn/ensemble/bagging.py", "observation": {"content": "ok", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 2, "action_type": "command", "content": "pytest sklearn/ensemble/tests/test_iforest.py", "observation": {"content": "AssertionError: IsolationForest has no attribute warm_start", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}, {"index": 3, "action_type": "finish", "content": "I have added warm_start support.", "observation": null, "timestamp": null, "metadata": {}, "failed": false}], "final_patch": "diff --git a/sklearn/ensemble/bagging.py b/sklearn/ensemble/bagging.py", "test_result": {"passed": false, "total_tests": 12, "passed_tests": 11, "failed_tests": 1, "error_tests": null, "raw_log": ""}, "resolved": false, "wall_time_seconds": null, "total_tokens": null, "total_cost_usd": null, "error": null, "metadata": {}, "step_count": 4, "produced_patch": true, "failed": true, "content_hash": "bb61379a0610a53d"}, {"run_id": "oh-reason-001", "agent": "openhands", "model": "claude-sonnet-4-6", "task": {"task_id": "django__django-11099", "source": "swe-bench", "repo": "django/django", "base_commit": null, "problem_statement": "UsernameValidator should not allow trailing newline.", "gold_patch": null, "test_directives": []}, "steps": [{"index": 0, "action_type": "file_read", "content": "django/contrib/auth/validators.py", "observation": {"content": "<contents>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 1, "action_type": "file_edit", "content": "changed regex from r'^[\\w.@+-]+$' to r'^[\\w.@+-]+\\Z'", "observation": {"content": "ok", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 2, "action_type": "command", "content": "pytest tests/auth_tests/test_validators.py", "observation": {"content": "1 failed: AssertionError: regex still matches 'abc\\n' (used $ semantics in test)", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}, {"index": 3, "action_type": "finish", "content": "Fixed the validator regex.", "observation": null, "timestamp": null, "metadata": {}, "failed": false}], "final_patch": "diff --git a/django/contrib/auth/validators.py", "test_result": {"passed": false, "total_tests": 8, "passed_tests": 7, "failed_tests": 1, "error_tests": null, "raw_log": ""}, "resolved": false, "wall_time_seconds": null, "total_tokens": null, "total_cost_usd": null, "error": null, "metadata": {}, "step_count": 4, "produced_patch": true, "failed": true, "content_hash": "6aebf0339b3470a5"}, {"run_id": "oh-verify-001", "agent": "openhands", "model": "claude-sonnet-4-6", "task": {"task_id": "matplotlib__matplotlib-23987", "source": "swe-bench", "repo": "matplotlib/matplotlib", "base_commit": null, "problem_statement": "Fix UserWarning when constrained_layout=False.", "gold_patch": null, "test_directives": []}, "steps": [{"index": 0, "action_type": "file_read", "content": "lib/matplotlib/figure.py", "observation": {"content": "<contents>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 1, "action_type": "file_edit", "content": "guarded the warning behind a None check", "observation": {"content": "ok", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 2, "action_type": "finish", "content": "The warning is now fixed; the change is complete.", "observation": null, "timestamp": null, "metadata": {}, "failed": false}], "final_patch": "diff --git a/lib/matplotlib/figure.py", "test_result": {"passed": false, "total_tests": null, "passed_tests": null, "failed_tests": null, "error_tests": null, "raw_log": ""}, "resolved": false, "wall_time_seconds": null, "total_tokens": null, "total_cost_usd": null, "error": null, "metadata": {}, "step_count": 3, "produced_patch": true, "failed": true, "content_hash": "b573dbb931c21c26"}, {"run_id": "oh-tool-001", "agent": "openhands", "model": "claude-sonnet-4-6", "task": {"task_id": "psf__requests-2317", "source": "swe-bench", "repo": "psf/requests", "base_commit": null, "problem_statement": "method = builtin_str(method) breaks on binary method.", "gold_patch": null, "test_directives": []}, "steps": [{"index": 0, "action_type": "file_edit", "content": "apply patch to requests/sessions.py (context lines mismatch)", "observation": {"content": "ERROR: patch does not apply; hunk #1 FAILED at 428", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}, {"index": 1, "action_type": "file_edit", "content": "apply patch to requests/sessions.py (context lines mismatch)", "observation": {"content": "ERROR: patch does not apply; hunk #1 FAILED at 428", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}, {"index": 2, "action_type": "file_edit", "content": "apply patch to requests/sessions.py (context lines mismatch)", "observation": {"content": "ERROR: patch does not apply; hunk #1 FAILED at 428", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}, {"index": 3, "action_type": "error", "content": "Giving up after repeated patch failures.", "observation": null, "timestamp": null, "metadata": {}, "failed": false}], "final_patch": null, "test_result": {"passed": false, "total_tests": null, "passed_tests": null, "failed_tests": null, "error_tests": null, "raw_log": ""}, "resolved": false, "wall_time_seconds": null, "total_tokens": null, "total_cost_usd": null, "error": null, "metadata": {}, "step_count": 4, "produced_patch": false, "failed": true, "content_hash": "09eee4b13fef1648"}, {"run_id": "oh-scope-001", "agent": "openhands", "model": "claude-sonnet-4-6", "task": {"task_id": "internal__ticket-8842", "source": "swe-bench", "repo": "acme/widgets", "base_commit": null, "problem_statement": "Make the export faster.", "gold_patch": null, "test_directives": []}, "steps": [{"index": 0, "action_type": "file_read", "content": "exporter.py", "observation": {"content": "<contents>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 1, "action_type": "file_edit", "content": "added a CSV streaming buffer to speed up file write", "observation": {"content": "ok", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 2, "action_type": "command", "content": "pytest tests/test_export.py", "observation": {"content": "1 failed: test expects parallel DB fetch optimization, not file IO change", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}, {"index": 3, "action_type": "finish", "content": "Made the export faster by buffering writes.", "observation": null, "timestamp": null, "metadata": {}, "failed": false}], "final_patch": "diff --git a/exporter.py", "test_result": {"passed": false, "total_tests": 4, "passed_tests": 3, "failed_tests": 1, "error_tests": null, "raw_log": ""}, "resolved": false, "wall_time_seconds": null, "total_tokens": null, "total_cost_usd": null, "error": null, "metadata": {}, "step_count": 4, "produced_patch": true, "failed": true, "content_hash": "5e37515fdd524327"}, {"run_id": "oh-other-001", "agent": "openhands", "model": "claude-sonnet-4-6", "task": {"task_id": "astropy__astropy-14182", "source": "swe-bench", "repo": "astropy/astropy", "base_commit": null, "problem_statement": "Support header rows in RST writer.", "gold_patch": null, "test_directives": []}, "steps": [{"index": 0, "action_type": "file_read", "content": "astropy/io/ascii/rst.py", "observation": {"content": "<contents>", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 1, "action_type": "file_edit", "content": "partial edit", "observation": {"content": "ok", "exit_code": 0, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": false}, {"index": 2, "action_type": "command", "content": "pytest astropy/io/ascii/tests/test_rst.py", "observation": {"content": "mixed: 2 failed, 1 error, traceback truncated", "exit_code": 1, "truncated": false, "extra": {}}, "timestamp": null, "metadata": {}, "failed": true}], "final_patch": "diff --git a/astropy/io/ascii/rst.py", "test_result": {"passed": false, "total_tests": null, "passed_tests": null, "failed_tests": null, "error_tests": null, "raw_log": ""}, "resolved": false, "wall_time_seconds": null, "total_tokens": null, "total_cost_usd": null, "error": null, "metadata": {}, "step_count": 3, "produced_patch": true, "failed": true, "content_hash": "1c42dc083c207a39"}];
